### ISSUE TITLE
MILESTONE: Get to version 1

### ISSUE THREAD

**Issue by fefi42** [semi-technologies/weaviate-python-client#3]
- [x] Have all API features discussed with implemented @michaverhagen please add list
- [x] Have all API features discussed with @laura-ham for UX quality
- [ ] Unit tests for all features
- [x] CI pipeline for project
- [x] Publish version 1.0.0 on GitHub
- [x] Publish version 1.0.0 on pip

**Comment by fefi42** [comment]
First published version is `0.1.0` it has all features that where discussed with micha and some extra. With the first published version the API will only change between major versions.
Not all features are unit tested so far. From now on there is the policy that new features and bugs need to be covered by a test of some kind.
